language: node
nodejs:
  - 12.18.0
addons:
  sshknownhosts:
    - 134.122.39.75
branches:
  only:
  - master
  - ci_cd_liwg
before_install:
- openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv -in deploy.enc -out deploy -d
install:
- npm install --only=dev
beforescript:
- chmod 600 deploy && mv deploy ~/.ssh/idrsa
scripts:
- cd landing-page
- npm run build
after_success:
- ls
- "../scripts/deploy.sh"

