language: node

dist: xenial

node_js:
  - 12.18.0
addons:
  ssh_known_hosts:
    - $REMOTE_HOST

branches:
  only:
  - main
  - ci_cd_liwg

script:
- openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv -in deploy.enc -out deploy -d
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
# - cd scripts
# - sh server_deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/server_deploy
    on:
      all_branches: true