language: node

sudo: required

nodejs:
  - 12.18.0
addons:
  sshknownhosts:
    - 134.122.39.75
branches:
  only:
  - master
  - ci_cd_liwg
beforescript:
- openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv -in deploy.enc -out deploy -d
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
scripts:
- cd landing-page
- npm install
- npm run build
- cd ..
after_success:
- ls -a
- scripts/deploy.sh