language: node

sudo: required
dist: xenial

nodejs:
  - 12.18.0
addons:
  sshknownhosts:
    - 134.122.39.75
branches:
  only:
  - main
  - ci_cd_liwg
scripts:
- openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv -in deploy.enc -out deploy -d
- chmod 600 deploy && mv deploy ~/.ssh/id_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/deploy
    on:
      all_branches: true
    